# Generated by Django 2.2 on 2022-10-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ITEMs',
        ),
    ]
